name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]
  issues:
    types: [opened]

jobs:
  claude-assist:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude') || github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude') || github.event_name == 'pull_request' || github.event_name == 'issues'
    
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v1
        with:
          # Claude Code OAuth Token for MAX subscription
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # GitHub token for repository access
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Trigger phrase (default is @claude)
          trigger_phrase: "@claude"
          
          # Timeout in minutes
          timeout_minutes: 10
          
          # Mode: "tag" for simple responses, "agent" for complex tasks
          mode: "agent"